package shamu.media.render;

/** Toolkit class responsible for creating modeling objects based on a barycentric frame parametric procedure, such as a bezier triangle.
 *
 *  @author  Scott T. Carter
 *  @version 1.4
 */

public class BarycentricFrameToolkit extends ParametricToolkit {

   /**
    * The number of subdivisions used for procedural modeling by this barycentric frame toolkit.
    */

   protected int subdivisions;

   /**
    * Creates a barycentric frame toolkit having the underlying parametric procedure specified by the bezier triangle argument and the
    * number of subdivisions specified by the integer argument.
    *
    * @param bezierTriangle the bezier triangle specifying this barycentric frame toolkit.
    * @param subdivisions the number of subdivisions specifying this barycentric frame toolkit.
    */

   protected BarycentricFrameToolkit(BezierTriangle bezierTriangle, int subdivisions) {

	  super(bezierTriangle);

      this.subdivisions = subdivisions;

   }

   /**
    * Creates geometry data generated by the underlying barycentric frame prodecure associated with this toolkit.
    *
    * @return the geometry data structure generated by the underlying barycentric frame procedure associated with this toolkit.
    */

   public Geometry createGeometry() {

      Mesh mesh = new Mesh(Mesh.TRIANGLES);

      float lowerBoundsU1 = parametricProcedure.getLowerBoundsU1();
      float lowerBoundsU2 = parametricProcedure.getLowerBoundsU2();

      float upperBoundsU1 = parametricProcedure.getUpperBoundsU1();
      float upperBoundsU2 = parametricProcedure.getUpperBoundsU2();

      for(int i = 0; i <= subdivisions; i++) {
         for(int j = 0; j <= subdivisions - i; j++) {

            float u1 = lowerBoundsU1 + (upperBoundsU1 - lowerBoundsU1) * j / subdivisions;
            float u2 = lowerBoundsU2 + (upperBoundsU2 - lowerBoundsU2) * i / subdivisions;

            generateData(mesh, u1, u2);

            if(i != 0) {

               int[] nextFace1 = new int[3];

			      nextFace1[0] = (i * (2 * subdivisions + 3 - i)) / 2 + j;
               nextFace1[1] = ((i - 1) * (2 * subdivisions + 4 - i)) / 2 + j + 1;
               nextFace1[2] = nextFace1[1] - 1;

               mesh.addFace(nextFace1);

			   if(j != 0) {

			      int[] nextFace2 = new int[3];

               nextFace2[0] = nextFace1[0] - 1;
               nextFace2[1] = nextFace1[0];
			      nextFace2[2] = nextFace1[2];

			      mesh.addFace(nextFace2);

			   }

		    }

	     }

      }


/*

      float x1 = parametricProcedure.mapX(1, 0);
      float y1 = parametricProcedure.mapY(1, 0);
      float z1 = parametricProcedure.mapZ(1, 0);

      float x2 = parametricProcedure.mapX(0, 1);
      float y2 = parametricProcedure.mapY(0, 1);
      float z2 = parametricProcedure.mapZ(0, 1);

      float x3 = parametricProcedure.mapX(0, 0);
      float y3 = parametricProcedure.mapY(0, 0);
      float z3 = parametricProcedure.mapZ(0, 0);

      mesh.addVertex(x1, y1, z1);
      mesh.addVertex(x2, y2, z2);
      mesh.addVertex(x3, y3, z3);

//      mesh.addVertex(-32.0f, 32.0f, 0.0f);
//      mesh.addVertex(32.0f, 32.0f, 0.0f);
//      mesh.addVertex(0.0f, -32.0f, 0.0f);

      mesh.addNormal(0.0f, 0.0f, -1.0f);
      mesh.addNormal(0.0f, 0.0f, -1.0f);
      mesh.addNormal(0.0f, 0.0f, -1.0f);

      mesh.addFace(new int[] {0, 1, 2});
*/
      return mesh;

   }

 //  public void computeNormal(float[] x_k, float[] normal) {}

   /**
    * Returns the number of subdivisions associated with this barycentric frame toolkit.
    *
    * @return the number of subdivisions associated with this barycentric frame toolkit.
    */

   public int getSubdivisions() { return subdivisions; }

   /**
    * Sets the number of subdivisions associated with this barycentric frame toolkit to the integer argument.
    *
    * @param subdivisions the value that the number of subdivisions associated with this barycentric frame toolkit is set to.
    */

   public void setSubdivisions(int subdivisions) { this.subdivisions = subdivisions; }

}