package shamu.media.render;

/** Class of overloaded static methods for computing basis functions that generate bezier and b-spline curves.
 *
 *  @author  Scott T. Carter
 *  @version 1.4
 */

public class CurveEvaluator {

   /**
    * Constructor with private scope to prevent unnecessary instantiation of this class
    */

   private CurveEvaluator() {}

   /**
    * Recursively calculates and returns the value of the triangular bernstein basis function that generates the bezier triangle argument having indices and order defined by the integer arguments
    * and evaluated at the floating point arguments.
    *
    * @param triangle the bezier triangle generated by the computed triangular bernstein basis function
    * @param i the i index of the triangular bernstein basis function that is evaluated.
    * @param j the j index of the triangular bernstein basis function that is evaluated.
    * @param k the k index of the triangular bernstein basis function that is evaluated.
    * @param m the order of the triangular bernstein basis function that is evaluated.
    * @param u1 the local variable u1 argument that the triangular bernstein basis function is evaluated at.
    * @param u2 the local variable u2 argument that the triangular bernstein basis function is evaluated at.
    * @return the value of the triangular bernstein basis function having order and index defined by the integer arguments evaluated at the floating point arguments.
    */

   public static float evaluate(BezierTriangle triangle, int i, int j, int k, int m, float u1, float u2) {

      if(m > 0 && (i >= 0 && j >= 0 && k >= 0) && (u1 >= 0 && u2 >= 0 && u1 + u2 <= 1))
         return u1 * evaluate(triangle, i - 1, j, k, m - 1, u1, u2) + u2 * evaluate(triangle, i, j - 1, k, m - 1, u1, u2) + (1 - u1 - u2) * evaluate(triangle, i, j, k - 1, m - 1, u1, u2);

      else if(m == 0 && (i == 0 && j == 0 && k == 0) && (u1 >= 0 && u2 >= 0 && u1 + u2 <= 1))
         return 1;

      else
         return 0;

   }

   /**
    * Recursively calculates and returns the value of the bernstein basis function that generates the bezier patch argument having order and index defined by the integer arguments
    * and evaluated at the floating point argument.
    *
    * @param patch the bezier patch generated by the computed bernstein basis function
    * @param i the index of the bernstein basis function that is evaluated.
    * @param k the order of the bernstein basis function that is evaluated.
    * @param t the parametric variable argument that the bernstein basis function is evaluated at.
    * @return the value of the bernstein basis function having order and index defined by the integer arguments evaluated at the floating point argument.
    */

   public static float evaluate(BezierPatch patch, int i, int k, float t) {

	  if(k > 0 && t >= 0 && t <= 1)
        return (1 - t) * evaluate(patch, i, k - 1, t) + t * evaluate(patch, i - 1, k - 1, t );

      else if(k == 0 && i == 0 && t >= 0 && t <= 1)
         return 1;

      else
         return 0;
   }

   /**
    * Recursively calculates and returns the value of the bernstein basis function that generates the 2D bezier curve argument having order and index defined by the integer arguments
    * and evaluated at the floating point argument.
    *
    * @param curve2D the 2D bezier curve generated by the computed bernstein basis function
    * @param i the index of the bernstein basis function that is evaluated.
    * @param k the order of the bernstein basis function that is evaluated.
    * @param t the parametric variable argument that the bernstein basis function is evaluated at.
    * @return the value of the bernstein basis function having order and index defined by the integer arguments evaluated at the floating point argument.
    */

   public static float evaluate(BezierCurve2D curve2D, int i, int k, float t) {

	  if(k > 0 && t >= 0 && t <= 1)
        return (1 - t) * evaluate(curve2D, i, k - 1, t) + t * evaluate(curve2D, i - 1, k - 1, t );

      else if(k == 0 && i == 0 && t >= 0 && t <= 1)
         return 1;

      else
         return 0;
   }

   /**
    * Recursively calculates and returns the value of the bernstein basis function that generates the 3D bezier curve argument having order and index defined by the integer arguments
    * and evaluated at the floating point argument.
    *
    * @param curve3D the 3D bezier curve generated by the computed bernstein basis function
    * @param i the index of the bernstein basis function that is evaluated.
    * @param k the order of the bernstein basis function that is evaluated.
    * @param t the parametric variable argument that the bernstein basis function is evaluated at.
    * @return the value of the bernstein basis function having order and index defined by the integer arguments evaluated at the floating point argument.
    */

   public static float evaluate(BezierCurve3D curve3D, int i, int k, float t) {

	  if(k > 0 && t >= 0 && t <= 1)
        return (1 - t) * evaluate(curve3D, i, k - 1, t) + t * evaluate(curve3D, i - 1, k - 1, t );

      else if(k == 0 && i == 0 && t >= 0 && t <= 1)
         return 1;

      else
         return 0;
   }

   /**
    * Recursively calculates and returns the value of the B-spline basis function that generates the 2D minimal spline argument having order and index defined by the integer arguments
    * and evaluated at the floating point argument.
    *
    * @param spline2D the 2D minimal spline generated by the computed B-spline basis function
    * @param i the index of the B-spline basis function that is evaluated.
    * @param k the order of the B-spline basis function that is evaluated.
    * @param t the parametric variable argument that the B-spline basis function is evaluated at.
    * @return the value of the B-spline basis function having order and index defined by the integer arguments evaluated at the floating point argument.
    */

   public static float evaluate(MinimalSpline2D spline2D, int i, int k, float t) {

      if(k > 0 && (t >= i && t < i + k + 1))
         return ((t - i) / k) * evaluate(spline2D, i, k - 1, t) + ((i + k + 1 - t) / k) * evaluate(spline2D, i + 1, k - 1, t );

      else if(k == 0 && (t >= i && t < i + 1))
         return 1;

      else
         return 0;

   }

   /**
    * Recursively calculates and returns the value of the B-spline basis function that generates the 3D minimal spline argument having order and index defined by the integer arguments
    * and evaluated at the floating point argument.
    *
    * @param spline3D the 2D minimal spline generated by the computed B-spline basis function
    * @param i the index of the B-spline basis function that is evaluated.
    * @param k the order of the B-spline basis function that is evaluated.
    * @param t the parametric variable argument that the B-spline basis function is evaluated at.
    * @return the value of the B-spline basis function having order and index defined by the integer arguments evaluated at the floating point argument.
    */

   public static float evaluate(MinimalSpline3D spline3D, int i, int k, float t) {

      if(k > 0 && (t >= i && t < i + k + 1))
         return ((t - i) / k) * evaluate(spline3D, i, k - 1, t) + ((i + k + 1 - t) / k) * evaluate(spline3D, i + 1, k - 1, t );

      else if(k == 0 && (t >= i && t < i + 1))
         return 1;

      else
         return 0;

   }

}