package shamu.media.render;

/** Toolkit class responsible for creating modeling objects based on a curvlinear frame parametric procedure.
 *
 *  @author  Scott T. Carter
 *  @version 1.4
 */

public class CurvilinearFrameToolkit extends ParametricToolkit {

   /**
    * The number of u1 local variable subdivisions used for procedural modeling by this curvilinear frame toolkit.
    */

   protected int subdivisionsU1;

   /**
    * The number of u2 local variable subdivisions used for procedural modeling by this curvilinear frame toolkit.
    */

   protected int subdivisionsU2;

   /**
    * Creates a curvlinear frame toolkit having the underlying parametric procedure specified by the bezier patch argument and the
    * number of u1 and u2 local variable subdivisions specified by the integer arguments.
    *
    * @param bezierPatch the bezier patch specifying this curvilinear frame toolkit.
    * @param subdivisionsU1 the number of u1 local variable subdivisions specifying this curvilinear frame toolkit.
    * @param subdivisionsU2 the number of u2 local variable subdivisions specifying this curvilinear frame toolkit.
    */

   protected CurvilinearFrameToolkit(BezierPatch bezierPatch, int subdivisionsU1, int subdivisionsU2) {

	  super(bezierPatch);

      this.subdivisionsU1 = subdivisionsU1;
      this.subdivisionsU2 = subdivisionsU2;

   }

   /**
    * Creates a curvlinear frame toolkit having the underlying parametric procedure specified by the generalized helicoid argument and the
    * number of u1 and u2 local variable subdivisions specified by the integer arguments.
    *
    * @param generalizedHelicoid the generalizedHelicoid specifying this curvilinear frame toolkit.
    * @param subdivisionsU1 the number of u1 local variable subdivisions specifying this curvilinear frame toolkit.
    * @param subdivisionsU2 the number of u2 local variable subdivisions specifying this curvilinear frame toolkit.
    */

   protected CurvilinearFrameToolkit(GeneralizedHelicoid generalizedHelicoid, int subdivisionsU1, int subdivisionsU2) {

	  super(generalizedHelicoid);

      this.subdivisionsU1 = subdivisionsU1;
      this.subdivisionsU2 = subdivisionsU2;

   }

   /**
    * Creates a curvlinear frame toolkit having the underlying parametric procedure specified by the monge patch argument and the
    * number of u1 and u2 local variable subdivisions specified by the integer arguments.
    *
    * @param mongePatch the monge patch specifying this curvilinear frame toolkit.
    * @param subdivisionsU1 the number of u1 local variable subdivisions specifying this curvilinear frame toolkit.
    * @param subdivisionsU2 the number of u2 local variable subdivisions specifying this curvilinear frame toolkit.
    */

   public CurvilinearFrameToolkit(MongePatch mongePatch, int subdivisionsU1, int subdivisionsU2) {

	  super(mongePatch);

      this.subdivisionsU1 = subdivisionsU1;
      this.subdivisionsU2 = subdivisionsU2;

   }

   /**
    * Creates a curvlinear frame toolkit having the underlying parametric procedure specified by the tube argument and the
    * number of u1 and u2 local variable subdivisions specified by the integer arguments.
    *
    * @param tube the tube specifying this curvilinear frame toolkit.
    * @param subdivisionsU1 the number of u1 local variable subdivisions specifying this curvilinear frame toolkit.
    * @param subdivisionsU2 the number of u2 local variable subdivisions specifying this curvilinear frame toolkit.
    */

   protected CurvilinearFrameToolkit(Tube tube, int subdivisionsU1, int subdivisionsU2) {

	  super(tube);

      this.subdivisionsU1 = subdivisionsU1;
      this.subdivisionsU2 = subdivisionsU2;

   }

   /**
    * Creates a curvlinear frame toolkit having the underlying parametric procedure specified by the seashell argument and the
    * number of u1 and u2 local variable subdivisions specified by the integer arguments.
    *
    * @param bezierPatch the seashell specifying this curvilinear frame toolkit.
    * @param subdivisionsU1 the number of u1 local variable subdivisions specifying this curvilinear frame toolkit.
    * @param subdivisionsU2 the number of u2 local variable subdivisions specifying this curvilinear frame toolkit.
    */

   protected CurvilinearFrameToolkit(Seashell seashell, int subdivisionsU1, int subdivisionsU2) {

	  super(seashell);

      this.subdivisionsU1 = subdivisionsU1;
      this.subdivisionsU2 = subdivisionsU2;

   }

   public CurvilinearFrameToolkit(PolarGrid polarGrid, int subdivisionsU1, int subdivisionsU2) {

     super(polarGrid);

      this.subdivisionsU1 = subdivisionsU1;
      this.subdivisionsU2 = subdivisionsU2;

   }

   /**
    * Creates geometry data generated by the underlying curvilinear frame prodecure associated with this toolkit.
    *
    * @return the geometry data structure generated by the underlying curvilinear frame procedure associated with this toolkit.
    */

   public Geometry createGeometry() {

      Mesh mesh = new Mesh(Mesh.TRIANGLES);

      float lowerBoundsU1 = parametricProcedure.getLowerBoundsU1();
      float lowerBoundsU2 = parametricProcedure.getLowerBoundsU2();

      float upperBoundsU1 = parametricProcedure.getUpperBoundsU1();
      float upperBoundsU2 = parametricProcedure.getUpperBoundsU2();

      for(int i = 0; i <= subdivisionsU2; i++) {
         for(int j = 0; j <= subdivisionsU1; j++) {

            float u1 = lowerBoundsU1 + (upperBoundsU1 - lowerBoundsU1) * j / subdivisionsU1;
            float u2 = lowerBoundsU2 + (upperBoundsU2 - lowerBoundsU2) * i / subdivisionsU2;

            generateData(mesh, u1, u2);

            if(i != 0 && j > 0) {

               int[] nextFace1 = new int[3];
               int[] nextFace2 = new int[3];

               nextFace1[0] = (subdivisionsU1 + 1) * i + j;
			      nextFace1[1] = (subdivisionsU1 + 1) * (i - 1) + j;
               nextFace1[2] = nextFace1[0] - 1;

               nextFace2[0] = nextFace1[2];
               nextFace2[1] = nextFace1[1];
			      nextFace2[2] = nextFace1[1] - 1;

			      mesh.addFace(nextFace1);
			      mesh.addFace(nextFace2);

		    }

         }

      }

      return mesh;

   }

//   public void computeNormal(float[] x_k, float[] normal) { parametricProcedure.computeNormal(x_k[0], x_k[1], x_k[2], normal); }

   //public void computeNormal(float[] x_k, float[] normal) {}

   /**
    * Returns the number of u1 local variable subdivisions associated with this curvilinear frame toolkit.
    *
    * @return the number of u1 local variable subdivisions associated with this curvilinear frame toolkit.
    */

   public int getSubdivisionsU1() { return subdivisionsU1; }

   /**
    * Returns the number of u2 local variable subdivisions associated with this curvilinear frame toolkit.
    *
    * @return the number of u2 local variable subdivisions associated with this curvilinear frame toolkit.
    */

   public int getSubdivisionsU2() { return subdivisionsU2; }

   /**
    * Sets the number of u1 local variable subdivisions associated with this curvilinear frame toolkit to the integer argument.
    *
    * @param subdivisionsU1 the value that the number of u1 local variable subdivisions associated with this curvilinear frame toolkit is set to.
    */

   public void setSubdivisionsU1(int subdivisionsU1) { this.subdivisionsU1 = subdivisionsU1; }

   /**
    * Sets the number of u2 local variable subdivisions associated with this curvilinear frame toolkit to the integer argument.
    *
    * @param subdivisionsU2 the value that the number of u2 local variable subdivisions associated with this curvilinear frame toolkit is set to.
    */

   public void setSubdivisionsU2(int subdivisionsU2) { this.subdivisionsU2 = subdivisionsU2; }

}