package shamu.media.render;

/** Subdivision toolkit class responsible for creating modeling objects based on a subdivision procedure that operates on a quadrilateral based control net.
 *
 *  @author  Scott T. Carter
 *  @version 1.4
 */

public class FourFoldSubdivisionToolkit extends SubdivisionToolkit {

   /**
    * Constructs a 4-fold subdivision toolkit having the underlying subdivision procedure specified by the Catmull-Clark subdivision procedure argument, and the number
    * of subdivision levels specified by the integer argument.
    *
    * @param subdivisionProcedure the Catmull-Clark subdivision procedure specifying this 4-fold subdivision toolkit.
    * @param subdivisionLevels the number of subdivision levels specifying this 4-fold subdivision toolkit.
    */

   public FourFoldSubdivisionToolkit(CatmullClarkSubdivisionProcedure subdivisionProcedure, int subdivisionLevels) { super(subdivisionProcedure, subdivisionLevels); }

   /**
    * Creates geometry data generated by the underlying subdivision prodecure associated with this 4-fold subdivision toolkit.
    *
    * @return the geometry data structure generated by the underlying subdivision procedure associated with this 3-fold subdivision toolkit.
    */

   public Geometry createGeometry() {

      SubdivisionMesh subdivisionMesh = new SubdivisionMesh(Mesh.QUADRILATERALS);

      float[][] controlNetVerticesAddress = new float[1][];
      int[][] controlNetIndexedFacesAddress = new int[1][];

      ControlNet controlNet = subdivisionProcedure.getControlNet();

      controlNet.getControlPointsAddress(controlNetVerticesAddress);
      controlNet.getControlIndicesAddress(controlNetIndexedFacesAddress);

      for(int i = 0; i < controlNet.getControlPointArrayStop(); i += 3) {

      	 float x = controlNetVerticesAddress[0][i + 0];
   		 float y = controlNetVerticesAddress[0][i + 1];
   		 float z = controlNetVerticesAddress[0][i + 2];

   		 subdivisionMesh.addVertex(x, y, z);

   	  }

      for(int i = 0; i < controlNet.getControlIndexArrayStop(); i += 4) {

   		 int[] indices = new int[4];

   		 indices[0] = controlNetIndexedFacesAddress[0][i + 0];
   		 indices[1] = controlNetIndexedFacesAddress[0][i + 1];
   		 indices[2] = controlNetIndexedFacesAddress[0][i + 2];
   		 indices[3] = controlNetIndexedFacesAddress[0][i + 3];

   		 subdivisionMesh.addFace(indices);

   	  }

      for(int i = 0; i < subdivisionLevels; i++)
         subdivisionProcedure.subdivide(subdivisionMesh);

      subdivisionProcedure.generateTangentBasisVectors(subdivisionMesh);
      subdivisionProcedure.generateNormalVectors(subdivisionMesh);

      return subdivisionMesh;

   }

   public void computeNormal(float[] u_k, float[] normal) {}   

}