package shamu.media.render;

/** Abstract procedural modeling class representing a family of surfaces generated by rotating a space curve about the y-axis and at the same time translating
 *  the generating curve in a direction parallel to the y-axis at a constant velocity. The generating curve is represented as a curve in (x, y) space and the
 *  u1 local variable of this surface corresponds to the rotation angle of the generating curve. The u2 local variable of this surface corresponds to the
 *  parametric variable of the generating curve.
 *
 *  @author  Scott T. Carter
 *  @version 1.4
 */

public class GeneralizedHelicoid extends ParametricProcedure {

   /**
    * The curve defined in 2D space used to generate this generalized helicoid.
    */

   protected ProfileCurve2D profileCurve;

   /**
    * The velocity at which the space curve associated with this generalized helicoid is translated while generating this generalized helicoid.
    */

   protected float slant;

   /**
    * Constructs a generalized helicoid with the profile curve specified by the profile curve argument.
    *
    * @param profileCurve the profile curve that the profile curve associated with this generalized helicoid is set to.
    */

   public GeneralizedHelicoid(ProfileCurve2D profileCurve) {

	  super();

	  this.profileCurve = profileCurve;

      this.lowerBoundsU2 = profileCurve.getLowerBoundsT();
      this.upperBoundsU2 = profileCurve.getUpperBoundsT();

   }

   /**
    * Constructs a generalized helicoid with the profile curve specified by the profile curve argumen and having the slant parameter and boundary determined by the floating point arguments.
    *
    * @param profileCurve the profile curve that the profile curve associated with this generalized helicoid is set to.
    * @param slant the value that the slant parameter associated with this generalized helicoid is set to.
    * @param lowerBoundsU1 the value that the u1 local variable lower bound that determines the boundary of this generalized helicoid is set to.
    * @param upperBoundsU1 the value that the u1 local variable upper bound that determines the boundary of this generalized helicoid is set to.
    */

   public GeneralizedHelicoid(ProfileCurve2D profileCurve, float slant, float lowerBoundsU1, float upperBoundsU1) {

	   super(lowerBoundsU1, profileCurve.getLowerBoundsT(), upperBoundsU1, profileCurve.getUpperBoundsT());

       this.profileCurve = profileCurve;
   	   this.slant = slant;

   }

   /**
    * Calculates and returns the x-coordinate of the point on this generalized helicoid mapped from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the x-coordinate of the point on this generalized helicoid mapped from the floating point arguments.
    */

   public float mapX(float u1, float u2) { return profileCurve.mapX(u2) * (float)Math.cos(u1); }

   /**
    * Calculates and returns the y-coordinate of the point on this generalized helicoid mapped from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the y-coordinate of the point on this generalized helicoid mapped from the floating point arguments.
    */

   public float mapY(float u1, float u2) { return slant * u1 + profileCurve.mapY(u2) ; }

   /**
    * Calculates and returns the z-coordinate of the point on this generalized helicoid mapped from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the z-coordinate of the point on this generalized helicoid mapped from the floating point arguments.
    */

   public float mapZ(float u1, float u2) { return profileCurve.mapX(u2) * (float)Math.sin(u1); }

   /**
    * Calculates and returns the x-coordinate of the point mapped by the partial derivative of this generalized helicoid with respect to the u1
    * local variable from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the x-coordinate of the point mapped by the partial derivative of this generalized helicoid with respect to the u1 local variable from the floating point arguments.
    */

   public float partialU1MapX(float u1, float u2) { return -profileCurve.mapX(u2) * (float)Math.sin(u1); }

   /**
    * Calculates and returns the y-coordinate of the point mapped by the partial derivative of this generalized helicoid with respect to the u1
    * local variable from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the y-coordinate of the point mapped by the partial derivative of this generalized helicoid with respect to the u1 local variable from the floating point arguments.
    */

   public float partialU1MapY(float u1, float u2) { return slant; }

   /**
    * Calculates and returns the z-coordinate of the point mapped by the partial derivative of this generalized helicoid with respect to the u1
    * local variable from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the z-coordinate of the point mapped by the partial derivative of this generalized helicoid with respect to the u1 local variable from the floating point arguments.
    */

   public float partialU1MapZ(float u1, float u2) { return profileCurve.mapX(u2) * (float)Math.cos(u1); }

   /**
    * Calculates and returns the x-coordinate of the point mapped by the partial derivative of this generalized helicoid with respect to the u2
    * local variable from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the x-coordinate of the point mapped by the partial derivative of this parametric surface with respect to the u2 local variable from the floating point arguments.
    */

   public float partialU2MapX(float u1, float u2) { return profileCurve.derivativeMapX(u2) * (float)Math.cos(u1); }

   /**
    * Calculates and returns the y-coordinate of the point mapped by the partial derivative of this generalized helicoid with respect to the u2
    * local variable from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the y-coordinate of the point mapped by the partial derivative of this generalized helicoid with respect to the u2 local variable from the floating point arguments.
    */

   public float partialU2MapY(float u1, float u2) { return profileCurve.derivativeMapY(u2); }

   /**
    * Calculates and returns the z-coordinate of the point mapped by the partial derivative of this generalized helicoid with respect to the u2
    * local variable from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the z-coordinate of the point mapped by the partial derivative of this generalized helicoid with respect to the u2 local variable from the floating point arguments.
    */

   public float partialU2MapZ(float u1, float u2) { return profileCurve.derivativeMapX(u2) * (float)Math.sin(u1); }

   /**
    * Returns the profile curve associated with this generalized helicoid.
    *
    * @return the profile curve associated with this generalized helicoid.
    */

   public ProfileCurve2D getProfileCurve2D() { return profileCurve; }

   /**
    * Returns the slant parameter associated with this generalized helicoid.
    *
    * @return the slant parameter associated with this generalized helicoid.
    */

   public float getSlant() { return slant; }

   /**
    * Sets the value of the slant parameter associated with this generalized helicoid to the floating point argument.
    *
    * @param slant the value that parameter the slant associated with this generalized helicoid is set to.
    */

   public void setSlant(float slant) { this.slant = slant; }

   /**
    * Sets the profile curve associated with this generalized helicoid to the profile curve argument.
    *
    * @param profileCurve the profile curve that the profile curve associated with this generalized helicoid is set to.
    */

   public void setProfileCurve(ProfileCurve2D profileCurve) { this.profileCurve = profileCurve; }

}

