package shamu.media.render;

/** Prodedural modeling class representing a family of surfaces generated by rotating a multiple of the normal and binormal vectors of a space
 *  curve's Frenet-Serret apparatus about the curve's tangent vector of the curve's Frenet-Serret apparatus at each point of the space curve.
 *  This family differs from the tube family in that the magnitude of the multiple applied to the normal and binormal vectors of the generating
 *  curve changes at a constant velocity, and this velocity is denoted the rho parameter of the seashell. The u1 local variable of this surface
 *  corresponds to the parametric variable of the generating curve, and the u2 local variable of this surface corresponds to the angle of rotation
 *  of the normal and binormal vectors about the generating curve.
 *
 *  @author  Scott T. Carter
 *  @version 1.4
 */

public class Seashell extends ParametricProcedure {

   /**
    * The curve defined in 3D space used to generate this seashell.
    */

   protected ProfileCurve3D profileCurve;

   /**
    * The rho parameter associated with this seashell.
    */

   protected float rho;

   /**
    * Constructs a seashell with the profile curve specified by the profile curve argument.
    *
    * @param profileCurve the profile curve that the profile curve associated with this seashell is set to.
    */

   public Seashell(ProfileCurve3D profileCurve) {

	  super();

	  this.profileCurve = profileCurve;

      this.lowerBoundsU1 = profileCurve.getLowerBoundsT();
      this.upperBoundsU1 = profileCurve.getUpperBoundsT();

   }

   /**
    * Constructs a seashell with the profile curve specified by the profile curve argument and having the rho parameter and boundary determined by the floating point arguments.
    *
    * @param profileCurve the profile curve that the profile curve associated with this seashell is set to.
    * @param rho the value that the rho parameter of this seashell is set to.
    * @param lowerBoundsU2 the value that the u2 local variable lower bound that determines the boundary of this seashell is set to.
    * @param upperBoundsU2 the value that the u2 local variable upper bound that determines the boundary of this seashell is set to.
    */

   public Seashell(ProfileCurve3D profileCurve, float rho, float lowerBoundsU2, float upperBoundsU2) {

      super(profileCurve.getLowerBoundsT(), lowerBoundsU2, profileCurve.getUpperBoundsT(), upperBoundsU2);

      this.profileCurve = profileCurve;
      this.rho = rho;

   }

   /**
    * Calculates and returns the x-coordinate of the point on this seashell that is mapped from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the x-coordinate of the point on this seashell that is mapped from the floating point arguments.
    */

   public float mapX(float u1, float u2) { return profileCurve.mapX(u1) + rho * u1 * ((float)Math.cos(u2) * profileCurve.normalMapX(u1) + (float)Math.sin(u2) * profileCurve.binormalMapX(u1)); }

   /**
    * Calculates and returns the y-coordinate of the point on this seashell that is mapped from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the y-coordinate of the point on this seashell that is mapped from the floating point arguments.
    */

   public float mapY(float u1, float u2) { return profileCurve.mapY(u1) + rho * u1 * ((float)Math.cos(u2) * profileCurve.normalMapY(u1) + (float)Math.sin(u2) * profileCurve.binormalMapY(u1)); }

   /**
    * Calculates and returns the z-coordinate of the point on this seashell that is mapped from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the z-coordinate of the point on this seashell that is mapped from the floating point arguments.
    */

   public float mapZ(float u1, float u2) { return profileCurve.mapZ(u1) + rho * u1 * ((float)Math.cos(u2) * profileCurve.normalMapZ(u1) + (float)Math.sin(u2) * profileCurve.binormalMapZ(u1)); }

   /**
    * Calculates and returns the x-coordinate of the point mapped by the partial derivative of this seashell with respect to the u1 local variable
    * from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the x-coordinate of the point mapped by the partial derivative of this seashell with respect to the u1 local variable from the floating point arguments.
    */

   public float partialU1MapX(float u1, float u2) { return profileCurve.derivativeMapX(u1) + rho * ((float)Math.cos(u2) * profileCurve.normalMapX(u1) + (float)Math.sin(u2) * profileCurve.binormalMapX(u1)) + rho * u1 * ((float)Math.cos(u2) * profileCurve.normalDerivativeMapX(u1) + (float)Math.sin(u2) * profileCurve.binormalDerivativeMapX(u1)); }

   /**
    * Calculates and returns the y-coordinate of the point mapped by the partial derivative of this seashell with respect to the u1 local variable
    * from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the y-coordinate of the point mapped by the partial derivative of this seashell with respect to the u1 local variable from the floating point arguments.
    */

   public float partialU1MapY(float u1, float u2) { return profileCurve.derivativeMapY(u1) +  rho * ((float)Math.cos(u2) * profileCurve.normalMapY(u1) + (float)Math.sin(u2) * profileCurve.binormalMapY(u1)) + rho * u1 * ((float)Math.cos(u2) * profileCurve.normalDerivativeMapY(u1) + (float)Math.sin(u2) * profileCurve.binormalDerivativeMapY(u1)); }

   /**
    * Calculates and returns the z-coordinate of the point mapped by the partial derivative of this seashell with respect to the u1 local variable
    * from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the z-coordinate of the point mapped by the partial derivative of this seashell with respect to the u1 local variable from the floating point arguments.
    */

   public float partialU1MapZ(float u1, float u2) { return profileCurve.derivativeMapZ(u1) + rho * ((float)Math.cos(u2) * profileCurve.normalMapZ(u1) + (float)Math.sin(u2) * profileCurve.binormalMapZ(u1)) + rho * u1 * ((float)Math.cos(u2) * profileCurve.normalDerivativeMapZ(u1) + (float)Math.sin(u2) * profileCurve.binormalDerivativeMapZ(u1)); }

   /**
    * Calculates and returns the x-coordinate of the point mapped by the partial derivative of this seashell with respect to the u2 local variable
    * from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the x-coordinate of the point mapped by the partial derivative of this seashell with respect to the u2 local variable from the floating point arguments.
    */

   public float partialU2MapX(float u1, float u2) { return rho * (-(float)Math.sin(u2) * profileCurve.normalMapX(u1) + (float)Math.cos(u2) * profileCurve.binormalMapX(u1)); }

   /**
    * Calculates and returns the y-coordinate of the point mapped by the partial derivative of this seashell with respect to the u2 local variable
    * from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the y-coordinate of the point mapped by the partial derivative of this seashell with respect to the u2 local variable from the floating point arguments.
    */

   public float partialU2MapY(float u1, float u2) { return rho * (-(float)Math.sin(u2) * profileCurve.normalMapY(u1) + (float)Math.cos(u2) * profileCurve.binormalMapY(u1)); }

   /**
    * Calculates and returns the z-coordinate of the point mapped by the partial derivative of this seashell with respect to the u2 local variable
    * from the floating point arguments.
    *
    * @param u1 the u1 local variable argument that this mapping is evaluated at.
    * @param u2 the u2 local variable argument that this mapping is evaluated at.
    * @return the z-coordinate of the point mapped by the partial derivative of this seashell with respect to the u2 local variable from the floating point arguments.
    */

   public float partialU2MapZ(float u1, float u2) { return rho * (-(float)Math.sin(u2) * profileCurve.normalMapZ(u1) + (float)Math.cos(u2) * profileCurve.binormalMapZ(u1)); }

   /**
    * Returns the profile curve associated with this seashell.
    *
    * @return the profile curve associated with this seashell.
    */

   public ProfileCurve3D getProfileCurve() { return profileCurve; }

   /**
    * Returns the rho parameter associated with this seashell.
    *
    * @return the rho parameter associated with this seashell.
    */

   public float getRho() { return rho; }

   /**
    * Sets the profile curve associated with this seashell to the profile curve argument.
    *
    * @param profileCurve the profile curve that the profile curve associated with this seashell is set to.
    */

   public void setProfileCurve(ProfileCurve3D profileCurve) { this.profileCurve = profileCurve; }

   /**
    * Sets the rho parameter associated with this seashell to the floating point argument.
    *
    * @param rho the value that the rho parameter associated with this seashell is set to.
    */

   public void setRho(float rho) { this.rho = rho; }

}
