package shamu.media.render;

/** Subdivision toolkit class responsible for creating modeling objects based on a subdivision procedure that operates on a triangle based control net.
 *
 *  @author  Scott T. Carter
 *  @version 1.4
 */

public class ThreeFoldSubdivisionToolkit extends SubdivisionToolkit {

   /**
    * Constructs a 3-fold subdivision toolkit having the underlying subdivision procedure specified by the Loop subdivision procedure argument, and the number
    * of subdivision levels specified by the integer argument.
    *
    * @param subdivisionProcedure the Loop subdivision procedure specifying this 3-fold subdivision toolkit.
    * @param subdivisionLevels the number of subdivision levels specifying this 3-fold subdivision toolkit.
    */

   public ThreeFoldSubdivisionToolkit(LoopSubdivisionProcedure subdivisionProcedure, int subdivisionLevels) { super(subdivisionProcedure, subdivisionLevels); }

   /**
    * Constructs a 3-fold subdivision toolkit having the underlying subdivision procedure specified by the spherical subdivision procedure argument, and the number
    * of subdivision levels specified by the integer argument.
    *
    * @param subdivisionProcedure the spherical subdivision procedure specifying this 3-fold subdivision toolkit.
    * @param subdivisionLevels the number of subdivision levels specifying this 3-fold subdivision toolkit.
    */

   public ThreeFoldSubdivisionToolkit(SphericalSubdivisionProcedure subdivisionProcedure, int subdivisionLevels) { super(subdivisionProcedure, subdivisionLevels); }

   /**
    * Creates geometry data generated by the underlying subdivision prodecure associated with this 3-fold subdivision toolkit.
    *
    * @return the geometry data structure generated by the underlying subdivision procedure associated with this 3-fold subdivision toolkit.
    */

   public Geometry createGeometry() {

      SubdivisionMesh subdivisionMesh = new SubdivisionMesh(Mesh.TRIANGLES);

      float[][] controlNetVerticesAddress = new float[1][];
      int[][] controlNetIndexedFacesAddress = new int[1][];

      ControlNet controlNet = subdivisionProcedure.getControlNet();

      controlNet.getControlPointsAddress(controlNetVerticesAddress);
      controlNet.getControlIndicesAddress(controlNetIndexedFacesAddress);

      for(int i = 0; i < controlNet.getControlPointArrayStop(); i += 3) {

      	 float x = controlNetVerticesAddress[0][i + 0];
   		 float y = controlNetVerticesAddress[0][i + 1];
   		 float z = controlNetVerticesAddress[0][i + 2];

   		 subdivisionMesh.addVertex(x, y, z);

   	  }

      for(int i = 0; i < controlNet.getControlIndexArrayStop(); i += 3) {

   		 int[] indices = new int[3];

   		 indices[0] = controlNetIndexedFacesAddress[0][i + 0];
   		 indices[1] = controlNetIndexedFacesAddress[0][i + 1];
   		 indices[2] = controlNetIndexedFacesAddress[0][i + 2];

   		 subdivisionMesh.addFace(indices);

   	  }

      for(int i = 0; i < subdivisionLevels; i++)
         subdivisionProcedure.subdivide(subdivisionMesh);

      subdivisionProcedure.generateTangentBasisVectors(subdivisionMesh);
      subdivisionProcedure.generateNormalVectors(subdivisionMesh);

      return subdivisionMesh;

   }

   public void computeNormal(float[] u_k, float[] normal) {}

}