package shamu.media.render;

/** Interface that classes implement to specify how modeling and underlying data structures are created. For example, different modeling procedures may need
 *  a different data structure for storing geometry data, so a class associated with each of these modeling procedures would need to be created that implements
 *  this interface.
 *
 *  @author  Scott T. Carter
 *  @version 1.4
 */

public interface ToolkitI {

   /**
    * Creates geometry data generated by the underlying procedural modeing object associated with instances of classes implementing this interface.
    *
    * @return the geometry data structure generated by the underlying procedural modeling object associated with instances of classes implementing this interface.
    */

   public Geometry createGeometry();

   public void computeNormal(float[] u_k, float[] normal);

}