package shamu.media.render;

/** Scene graph node subclass that represents a terminal node in a scene graph that is associated with a visible object in the virtual world
 *  containing procedural modeling and material information.
 *
 *  @author  Scott T. Carter
 *  @version 1.4
 */

public class VertexSystem extends Object3D {

   protected ToolkitI toolkit;

   public VertexSystem() { super(); }

   protected VertexSystem(int shadingAttribute) { super(shadingAttribute); }

   public VertexSystem(LoopSubdivisionProcedure procedure, int subdivisionLevels, int localShadingAttribute) {

      super(localShadingAttribute);

      //this.geometry = new ThreeFoldSubdivisionToolkit(procedure, subdivisionLevels).createGeometry(); 

      this.toolkit = new ThreeFoldSubdivisionToolkit(procedure, subdivisionLevels);

   }

   public VertexSystem(CatmullClarkSubdivisionProcedure procedure, int subdivisionLevels, int localShadingAttribute) {

      super(localShadingAttribute);

      //this.geometry = new FourFoldSubdivisionToolkit(procedure, subdivisionLevels).createGeometry(); 

      this.toolkit = new FourFoldSubdivisionToolkit(procedure, subdivisionLevels);

   }

   public VertexSystem(SphericalSubdivisionProcedure procedure, int subdivisionLevels, int localShadingAttribute) {

      super(localShadingAttribute);

      //this.geometry = new ThreeFoldSubdivisionToolkit(procedure, subdivisionLevels).createGeometry(); 

      this.toolkit = new ThreeFoldSubdivisionToolkit(procedure, subdivisionLevels);

   }

   public VertexSystem(BezierTriangle bezierTriangle, int subdivisions, int localShadingAttribute) {

      super(localShadingAttribute);

      //this.geometry = new BarycentricFrameToolkit(bezierTriangle, subdivisions).createGeometry(); 
   
      this.toolkit = new BarycentricFrameToolkit(bezierTriangle, subdivisions);

   }

   public VertexSystem(BezierPatch bezierPatch, int subdivisionsU1, int subdivisionsU2, int localShadingAttribute) { 

      super(localShadingAttribute);

      //this.geometry = new CurvilinearFrameToolkit(bezierPatch, subdivisionsU1, subdivisionsU2).createGeometry(); 

      this.toolkit = new CurvilinearFrameToolkit(bezierPatch, subdivisionsU1, subdivisionsU2);

   }

   public VertexSystem(GeneralizedHelicoid generalizedHelicoid, int subdivisionsU1, int subdivisionsU2, int localShadingAttribute) { 

      super(localShadingAttribute);

      //this.geometry = new CurvilinearFrameToolkit(generalizedHelicoid, subdivisionsU1, subdivisionsU2).createGeometry(); 

      this.toolkit = new CurvilinearFrameToolkit(generalizedHelicoid, subdivisionsU1, subdivisionsU2);

   }

   public VertexSystem(MongePatch mongePatch, int subdivisionsU1, int subdivisionsU2, int localShadingAttribute) { 

      super(localShadingAttribute);

      //this.geometry = new CurvilinearFrameToolkit(mongePatch, subdivisionsU1, subdivisionsU2).createGeometry(); 

      this.toolkit = new CurvilinearFrameToolkit(mongePatch, subdivisionsU1, subdivisionsU2);

   }

   public VertexSystem(Tube tube, int subdivisionsU1, int subdivisionsU2, int localShadingAttribute) { 

      super(localShadingAttribute);

      //this.geometry = new CurvilinearFrameToolkit(tube, subdivisionsU1, subdivisionsU2).createGeometry(); 

      this.toolkit = new CurvilinearFrameToolkit(tube, subdivisionsU1, subdivisionsU2);

   }

   public VertexSystem(Seashell seashell, int subdivisionsU1, int subdivisionsU2, int localShadingAttribute) { 

      super(localShadingAttribute);

      //this.geometry = new CurvilinearFrameToolkit(seashell, subdivisionsU1, subdivisionsU2).createGeometry(); 

      this.toolkit = new CurvilinearFrameToolkit(seashell, subdivisionsU1, subdivisionsU2);

   }

   public VertexSystem(PolarGrid polarGrid, int subdivisionsU1, int subdivisionsU2, int localShadingAttribute) {

      super(localShadingAttribute);

      //this.geometry = new CurvilinearFrameToolkit(polarGrid, subdivisionsU1, subdivisionsU2).createGeometry(); 

      this.toolkit = new CurvilinearFrameToolkit(polarGrid, subdivisionsU1, subdivisionsU2);


   }


   /**
    * Constructs a 3D object whose geometry is generated by the Loop subdivision procedure argument with the level of detail specified by the integer argument.
    *
    * @param procedure the Loop subdivision procedure that generates the geometry of this 3D object.
    * @param subdivisionLevels the number of subdivision levels used to generate the geometry of this 3D object.
    */

   public VertexSystem(LoopSubdivisionProcedure procedure, int subdivisionLevels) { 

      //this.geometry = new ThreeFoldSubdivisionToolkit(procedure, subdivisionLevels).createGeometry(); 

      this.toolkit = new ThreeFoldSubdivisionToolkit(procedure, subdivisionLevels);

   }

   /**
    * Constructs a 3D object whose geometry is generated by the Catmull-Clark subdivision procedure with the level of detail specified by the integer argument.
    *
    * @param procedure the Catmull-Clark subdivision procedure that generates the geometry of this 3D object.
    * @param subdivisionLevels the number of subdivision levels used to generate the geometry of this 3D object.
    */

   public VertexSystem(CatmullClarkSubdivisionProcedure procedure, int subdivisionLevels) { 

      //this.geometry = new FourFoldSubdivisionToolkit(procedure, subdivisionLevels).createGeometry(); 

      this.toolkit =  new FourFoldSubdivisionToolkit(procedure, subdivisionLevels);

   }

   /**
    * Constructs a 3D object whose geometry is generated by the spherical subdivision procedure with the level of detail specified by the integer argument.
    *
    * @param procedure the spherical subdivision procedure that generates the geometry of this 3D object.
    * @param subdivisionLevels the number of subdivision levels used to generate the geometry of this 3D object.
    */

   public VertexSystem(SphericalSubdivisionProcedure procedure, int subdivisionLevels) { 

      //this.geometry = new ThreeFoldSubdivisionToolkit(procedure, subdivisionLevels).createGeometry(); 

      this.toolkit = new ThreeFoldSubdivisionToolkit(procedure, subdivisionLevels);

   }

   /**
    * Constructs a 3D object whose geometry is generated by the Bezier triangle procedure with the level of detail specified by the integer argument.
    *
    * @param procedure the Bezier triangle procedure that generates the geometry of this 3D object.
    * @param subdivisionLevels the number of subdivision levels used to generate the geometry of this 3D object.
    */

   public VertexSystem(BezierTriangle bezierTriangle, int subdivisions) { 

      //this.geometry = new BarycentricFrameToolkit(bezierTriangle, subdivisions).createGeometry(); 

      this.toolkit = new BarycentricFrameToolkit(bezierTriangle, subdivisions);

   }

   /**
    * Constructs a 3D object whose geometry is generated by the Bezier patch procedure with the level of detail specified by the integer arguments.
    *
    * @param procedure the Bezier triangle procedure that generates the geometry of this 3D object.
    * @param subdivisionsU1 the number of u1 local variable subdivisions used to generate the geometry of this 3D object.
    * @param subdivisionsU2 the number of u2 local variable subdivisions used to generate the geometry of this 3D object.
    */

   public VertexSystem(BezierPatch bezierPatch, int subdivisionsU1, int subdivisionsU2) { 

      //this.geometry = new CurvilinearFrameToolkit(bezierPatch, subdivisionsU1, subdivisionsU2).createGeometry(); 

      this.toolkit = new CurvilinearFrameToolkit(bezierPatch, subdivisionsU1, subdivisionsU2);

   }

   /**
    * Constructs a 3D object whose geometry is generated by the generalized helicoid procedure with the level of detail specified by the integer arguments.
    *
    * @param procedure the generalized helicoid procedure that generates the geometry of this 3D object.
    * @param subdivisionsU1 the number of u1 local variable subdivisions used to generate the geometry of this 3D object.
    * @param subdivisionsU2 the number of u2 local variable subdivisions used to generate the geometry of this 3D object.
    */

   public VertexSystem(GeneralizedHelicoid generalizedHelicoid, int subdivisionsU1, int subdivisionsU2) { 

      //this.geometry = new CurvilinearFrameToolkit(generalizedHelicoid, subdivisionsU1, subdivisionsU2).createGeometry(); 

      this.toolkit = new CurvilinearFrameToolkit(generalizedHelicoid, subdivisionsU1, subdivisionsU2);

   }

   /**
    * Constructs a 3D object whose geometry is generated by the Monge patch procedure with the level of detail specified by the integer arguments.
    *
    * @param procedure the Monge patch procedure that generates the geometry of this 3D object.
    * @param subdivisionsU1 the number of u1 local variable subdivisions used to generate the geometry of this 3D object.
    * @param subdivisionsU2 the number of u2 local variable subdivisions used to generate the geometry of this 3D object.
    */

   public VertexSystem(MongePatch mongePatch, int subdivisionsU1, int subdivisionsU2) { 

      //this.geometry = new CurvilinearFrameToolkit(mongePatch, subdivisionsU1, subdivisionsU2).createGeometry(); 

      this.toolkit = new CurvilinearFrameToolkit(mongePatch, subdivisionsU1, subdivisionsU2);

   }

   /**
    * Constructs a 3D object whose geometry is generated by the tube procedure with the level of detail specified by the integer arguments.
    *
    * @param procedure the tube procedure that generates the geometry of this 3D object.
    * @param subdivisionsU1 the number of u1 local variable subdivisions used to generate the geometry of this 3D object.
    * @param subdivisionsU2 the number of u2 local variable subdivisions used to generate the geometry of this 3D object.
    */

   public VertexSystem(Tube tube, int subdivisionsU1, int subdivisionsU2) { 

      //this.geometry = new CurvilinearFrameToolkit(tube, subdivisionsU1, subdivisionsU2).createGeometry(); 

      this.toolkit = new CurvilinearFrameToolkit(tube, subdivisionsU1, subdivisionsU2);

   }

   /**
    * Constructs a 3D object whose geometry is generated by the seashell procedure with the level of detail specified by the integer arguments.
    *
    * @param procedure the seashell procedure that generates the geometry of this 3D object.
    * @param subdivisionsU1 the number of u1 local variable subdivisions used to generate the geometry of this 3D object.
    * @param subdivisionsU2 the number of u2 local variable subdivisions used to generate the geometry of this 3D object.
    */

   public VertexSystem(Seashell seashell, int subdivisionsU1, int subdivisionsU2) { 

      //this.geometry = new CurvilinearFrameToolkit(seashell, subdivisionsU1, subdivisionsU2).createGeometry(); 

      this.toolkit = new CurvilinearFrameToolkit(seashell, subdivisionsU1, subdivisionsU2);


   }

   public VertexSystem(PolarGrid polarGrid, int subdivisionsU1, int subdivisionsU2) { 

     // this.geometry = new CurvilinearFrameToolkit(polarGrid, subdivisionsU1, subdivisionsU2).createGeometry(); 

      this.toolkit = new CurvilinearFrameToolkit(polarGrid, subdivisionsU1, subdivisionsU2);

   }


   /**
    * Generates geometry data and updates the current state of the notifier argument. Notifies the notifier argument's registered view objects of changes needed to be made to their frame buffers.
    *
	* @param notifier the render notifier whose state information is updated and who notifies view objects of changes needed to made to their frame buffers.
    * @param currentMatrix the matrix that is set as the current world transformation in the state information of the notifier argument.
    */

   protected void traverse(RenderNotifier notifier, Matrix4D currentMatrix) {

      Geometry geometry = toolkit.createGeometry();

     // geometry.apply(new Matrix3D(16, 16, 16));

     Matrix4D worldToObjectMatrix = new Matrix4D();
     currentMatrix.invert(worldToObjectMatrix);

//     java.util.LinkedList<WorldPair> visuals  = notifier.getVisuals();


  //   visuals.add(new WorldPair(this, worldToObjectMatrix));
     //visuals.add(this);
     //visuals.add(worldToObjectMatrix);



      notifier.setCurrentGeometry(geometry);
      notifier.setCurrentToolkit(toolkit);
      notifier.setCurrentMatrix(currentMatrix);

      notifier.setCurrentMotionAttributes(motionAttributes);
      notifier.setCurrentRenderingAttributes(renderingAttributes);

      notifier.setCurrentTextureMapArray(textureMapArray);
      notifier.setCurrentTextureAttributesArray(textureAttributesArray);

      notifier.setCurrentDiffuseCoefficientR(diffuseCoefficientR);
      notifier.setCurrentDiffuseCoefficientG(diffuseCoefficientG);
      notifier.setCurrentDiffuseCoefficientB(diffuseCoefficientB);

      notifier.setCurrentSpecularCoefficientR(specularCoefficientR);
      notifier.setCurrentSpecularCoefficientG(specularCoefficientG);
      notifier.setCurrentSpecularCoefficientB(specularCoefficientB);

      notifier.setCurrentEmissiveCoefficientR(emissiveCoefficientR);
      notifier.setCurrentEmissiveCoefficientG(emissiveCoefficientG);
      notifier.setCurrentEmissiveCoefficientB(emissiveCoefficientB);

      notifier.setCurrentFresnelCoefficientR(fresnelCoefficientR);
      notifier.setCurrentFresnelCoefficientG(fresnelCoefficientG);
      notifier.setCurrentFresnelCoefficientB(fresnelCoefficientB);

      notifier.setCurrentDiffuseReflectivityR(diffuseReflectivityR);
      notifier.setCurrentDiffuseReflectivityG(diffuseReflectivityG);
      notifier.setCurrentDiffuseReflectivityB(diffuseReflectivityB);

      notifier.setCurrentShininess(shininess);
      notifier.setCurrentMicrofacetRoughness(microfacetRoughness);

      notifier.notifyObservers();

   }

   public ToolkitI getToolkit() { return this.toolkit; }

   public void setToolkit(ToolkitI toolkit) { this.toolkit = toolkit; }

}
